spring:
    profiles:
        action:
        - dev
---
spring:
    profiles: dev #开发环境
    application:
      name: microservicecloud-config-zengyunhua-dev
---
spring:
    profiles: test #开发环境
    application:
      name: microservicecloud-config-zengyunhua-test
